export const GET_PIZZAS_REQUEST="GET_PIZZAS_REQUEST"

export const GET_PIZZAS_SUCCESS="GET_PIZZAS_SUCCESS"

export const GET_PIZZAS_FAILED="GET_PIZZAS_FAILED"

export const ADD_PIZZA_REUEST="ADD_PIZZA_REUEST"

export const ADD_PIZZA_SUCCESS="ADD_PIZZA_SUCCESS"

export const ADD_PIZZA_FAILED="ADD_PIZZA_FAILED"

export const GET_PIZZABYID_REQUEST="GET_PIZZABYID_REQUEST"

export const GET_PIZZABYID_SUCCESS="GET_PIZZABYID_SUCCESS"

export const GET_PIZZABYID_FAILED="GET_PIZZABYID_FAILED"

export const EDIT_PIZZA_REQUEST="EDIT_PIZZA_REQUEST"

export const EDIT_PIZZA_SUCCESS="EDIT_PIZZA_SUCCESS"

export const EDIT_PIZZA_FAILED="EDIT_PIZZA_FAILED"